### ISSUE TITLE
Setting file

### ISSUE THREAD

**Issue by giginet** [giginet/Toybox#27]
locate on `~/.toybox/config.toml`

```toml
defaultXcodePath = "/Applications/Xcode-11.1.app"
defaultPlatform = "macOS"
autoSave = true
```
